spring:
  application:
    name: yuri

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # 数据源设置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zyl?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yuri
    type: com.alibaba.druid.pool.DruidDataSource

  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      table-underline: true
      logic-not-delete-value: false
      logic-delete-value: true
  configuration:
    map-underscore-to-camel-case: true

  # 打印sql内容 需要pol 开启依赖
  p6spy:
    # 日志格式
    log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
    # 自定义日志类
    logging: custom
    custom-appender-class: com.example.testinit.config.StdoutLogger

knife4j:
  enable: true # 开启文档接口增强功能

server:
  tomcat:
    max-http-header-size: 81920
    max-http-response-header-size: 81920
    max-http-form-post-size: 81920

  port: 2078

#system:
#  project-path: "/home/yuri/love-yuri/mathExamMaster/kotlin/src/main/kotlin"
#  upload-path: "/home/yuri/love-yuri/mathExamMaster/files/upload"

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true