packages:
  - "internal/*"
  - "internal/lint-configs/*"
  - "packages/*"
  - "packages/yuri/*"
  - "packages/@core/base/*"
  - "packages/@core/ui-kit/*"
  - "packages/@core/forward/*"
  - "packages/@core/*"
  - "packages/effects/*"
  - "packages/business/*"
  - "scripts/*"
  - "root"
  - "student"
