spring:
  application:
    name: yuri

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  # 数据源设置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zyl?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yuri
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  global-config:
    db-config:
      table-underline: true
      logic-not-delete-value: false
      logic-delete-value: true
  configuration:
    map-underscore-to-camel-case: true

  # 打印sql内容 需要pol 开启依赖
  p6spy:
    # 日志格式
    log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
    # 自定义日志类
    logging: custom
    custom-appender-class: com.example.testinit.config.StdoutLogger

knife4j:
  enable: true # 开启文档接口增强功能

server:
  port: 2078

system:
  project-path: "/home/yuri/love-yuri/mathExamMaster/kotlin/src/main/kotlin"
  upload-path: "/home/yuri/love-yuri/mathExamMaster/files/upload"

