spring:
  application:
    name: yuri

  # 数据源设置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zyl?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yuri
    type: com.alibaba.druid.pool.DruidDataSource


knife4j:
  enable: true # 开启文档接口增强功能

mybatis-plus:
  global-config:
    db-config:
      table-underline: true
      logic-not-delete-value: false
      logic-delete-value: true
  configuration:
    map-underscore-to-camel-case: true