name: 'publish'

on:
  push:
    branches:
      - main

    paths:
      - '__VERSION__'  # 仅当 __VERSION__ 文件发生更改时触发

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置node环境
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 安装rust工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: ubuntu 安装依赖
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 适用于 Tauri v1 - webkitgtk 4.1 适用于 Tauri v2.

      - name: 安装pnpm
        run: npm install -g pnpm

      - name: 安装前端依赖
        working-directory: admin/
        run: pnpm install

      - name: 获取最近的提交信息(Windows)
        if: runner.os == 'Windows'
        run: |
          $commits = git log --oneline --since="1 week ago"
          echo "COMMITS=$commits" >> $env:GITHUB_ENV

      - name: 获取最近的提交信息(Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          COMMITS=$(git log --oneline --since="1 week ago")
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV

      - name: 开始打包应用
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: |
            ## 最近更新：
            ${{ env.COMMITS }}
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
